thread 'main' panicked at 'panicking from libcore', $DIR/panic_abort3.rs:LL:CC
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: abnormal termination: the program aborted execution
  --> RUSTLIB/panic_abort/src/lib.rs:LL:CC
   |
LL |                 ABORT();
   | ^ the program aborted execution
   |
   = note: inside `panic_abort::__rust_start_panic::abort`
   = note: inside `panic_abort::__rust_start_panic`
   = note: inside `std::panicking::rust_panic`
   = note: inside `std::panicking::rust_panic_with_hook`
   = note: inside closure
   = note: inside `std::sys_common::backtrace::__rust_end_short_backtrace::<[closure@std::panicking::begin_panic_handler::{closure#0}], !>`
   = note: inside `std::panicking::begin_panic_handler`
note: inside `main`
  --> $DIR/panic_abort3.rs:LL:CC
   |
LL |     core::panic!("panicking from libcore");
   | ^
   = note: this error originates in the macro `$crate::panic::panic_2015` which comes from the expansion of the macro `core::panic` (in Nightly builds, run with -Z macro-backtrace for more info)

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace

error: aborting due to previous error

